<a href="https://colab.research.google.com/github/mieseung/Deep-learning-zero-to-all/blob/main/LAB01_1_Tensor_manipulation(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1D Array with numpy with numpy



In [ ]:
import numpy as np
import torch

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1] ) # element
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) # slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


# 1D Array with pytorch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # element
print(t[2:5], t[4:-1]) # slicing
print(t[:2], t[3:]) # slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


# Broadcasting
텐서간의 크기가 달라도 연산이 가능하게끔 해줌.
사용자 입장에서 주의해서 사용해야함. 실수를 의도와 다르게 연산이 되면 결과값이 잘못 나올 수 있음.

In [ ]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# Vector + shape
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2x1 vector + 1x2 vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


# Multiplication vs Matrix Multiplication

In [ ]:
# matrix multiplication
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1.matmul(m2))

# multiplication
m1 = torch.FloatTensor([[1, 2], [3, 4]]) # 2 * 2
m2 = torch.FloatTensor([[1], [2]]) # 2 * 1
print(m1 * m2) # 2 * 2

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


# Mean

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())
print(t.mean(dim=0)) # columnwise mean
print(t.mean(dim=1)) # rowwise mean
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Sum

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum())

tensor(10.)


In [ ]:
print(t.sum())
print(t.sum(dim=0)) # columnwise mean
print(t.sum(dim=1)) # rowwise mean
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and Argmax
Argmax : max인 index 값을 return

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max())

tensor(4.)


In [ ]:
print(t.max(dim = 0)) # returns two values when dimension is specified : max and argmax
print('Max : ', t.max(dim=0)[0])
print('ArgMax : ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max :  tensor([3., 4.])
ArgMax :  tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
